### ISSUE TITLE
Max Seat check

### ISSUE THREAD

**Issue by salman96900** [murgupluoglu/seatview-android#1]
How to achieve max seat limit. Is there function available ? How releasedSeat function work ? I called releasedSeatat very first line in seatSelected callback with max check but it did not show any update on ui :/

**Comment by murgupluoglu** [comment]
You must contol at canSelectSeat, you can check how many seats selected before and allow or not at this point. 

```kotlin
override fun canSelectSeat(clickedSeat: Seat, selectedSeats: HashMap<String, Seat>): Boolean {
           if(selectedSeats.size <= 5){
               return true
           }
               Toast.makeText(getApplicationContext(),"You can't select more than 5 seats",Toast.LENGTH_SHORT).show()
           return false
 }
```
